version: '3'
services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge